version: '3.8'
#docker-compose up -d
services:
  mysql:
    image: mysql:8.0
    container_name: river-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: river
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - /Users/apple/river-docker/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: river-redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/apple/river-docker/redis:/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: river-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "5050:8080"
    restart: unless-stopped
