server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration
  # 数据源配置项
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:admin}
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 10
        max-active: 50
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 1800000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:river}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: ${MYSQL_USER:root}
          password: ${MYSQL_PASSWORD}

  # Redis 配置
  data:
    redis:
      host: redis
      port: 6379

--- #################### 定时任务相关配置 ####################
spring:
  quartz:
    auto-startup: true
    scheduler-name: schedulerName
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true
            clusterCheckinInterval: 15000
            misfireThreshold: 60000
          threadPool:
            threadCount: 25
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool
    jdbc:
      initialize-schema: NEVER

--- #################### 服务保障相关配置 ####################
lock4j:
  acquire-timeout: 3000
  expire: 30000

--- #################### 监控相关配置 ####################
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info

# 日志文件配置
logging:
  file:
    name: /app/logs/${spring.application.name}.log
  level:
    root: INFO
    com.river: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR

debug: false

--- #################### 微信公众号、小程序相关配置 ####################
wx:
  mp: # 公众号配置
    app-id: ${WX_MP_APP_ID:}
    secret: ${WX_MP_SECRET:}
    config-storage:
      type: RedisTemplate
      key-prefix: wx
      http-client-type: HttpClient
  miniapp: # 小程序配置
    appid: ${WX_MINIAPP_APP_ID:}
    secret: ${WX_MINIAPP_SECRET:}
    config-storage:
      type: RedisTemplate
      key-prefix: wa
      http-client-type: HttpClient

--- #################### 芋道相关配置 ####################
river:
  captcha:
    enable: false
  security:
    mock-enable: false
  pay:
    order-notify-url: ${PAY_ORDER_NOTIFY_URL:https://deals.ecommica.com/admin-api/pay/notify/order}
    refund-notify-url: ${PAY_REFUND_NOTIFY_URL:https://deals.ecommica.com/admin-api/pay/notify/refund}
    transfer-notify-url: ${PAY_TRANSFER_NOTIFY_URL:https://deals.ecommica.com/admin-api/pay/notify/transfer}
  access-log:
    enable: true
  demo: false
  mediabuy:
    click-log-file: /app/logs/mediabuy-click.log
  wxa-code:
    env-version: release # 小程序版本: 正式版为 "release"
  wxa-subscribe-message:
    miniprogram-state: formal # 跳转小程序类型：正式版为 "formal"
  tencent-lbs-key: ${TENCENT_LBS_KEY:}

--- #################### 社交登录相关配置 ####################
justauth:
  enabled: true
  type:
    DINGTALK:
      client-id: ${DINGTALK_CLIENT_ID:}
      client-secret: ${DINGTALK_CLIENT_SECRET:}
      ignore-check-redirect-uri: true
    WECHAT_ENTERPRISE:
      client-id: ${WECHAT_ENTERPRISE_CLIENT_ID:}
      client-secret: ${WECHAT_ENTERPRISE_CLIENT_SECRET:}
      agent-id: ${WECHAT_ENTERPRISE_AGENT_ID:}
      ignore-check-redirect-uri: true
    WECHAT_MINI_PROGRAM:
      client-id: ${wx.miniapp.appid}
      client-secret: ${wx.miniapp.secret}
      ignore-check-redirect-uri: true
      ignore-check-state: true
    WECHAT_MP:
      client-id: ${wx.mp.app-id}
      client-secret: ${wx.mp.secret}
      ignore-check-redirect-uri: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:'
    timeout: 24h
